package com.anhkhoa.WebNT.mapper;

import com.anhkhoa.WebNT.model.account;
import com.anhkhoa.WebNT.model.accountExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface accountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    long countByExample(accountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    int deleteByExample(accountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    int insert(account row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    int insertSelective(account row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    List<account> selectByExample(accountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    account selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    int updateByExampleSelective(@Param("row") account row, @Param("example") accountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    int updateByExample(@Param("row") account row, @Param("example") accountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    int updateByPrimaryKeySelective(account row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    int updateByPrimaryKey(account row);
}