package com.anhkhoa.WebNT.mapper;

import com.anhkhoa.WebNT.model.banthanhphan;
import com.anhkhoa.WebNT.model.banthanhphanExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface banthanhphanMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banthanhphan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	long countByExample(banthanhphanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banthanhphan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	int deleteByExample(banthanhphanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banthanhphan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	int deleteByPrimaryKey(Integer mabanthanhphan);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banthanhphan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	int insert(banthanhphan row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banthanhphan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	int insertSelective(banthanhphan row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banthanhphan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	List<banthanhphan> selectByExampleWithBLOBs(banthanhphanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banthanhphan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	List<banthanhphan> selectByExample(banthanhphanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banthanhphan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	banthanhphan selectByPrimaryKey(Integer mabanthanhphan);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banthanhphan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") banthanhphan row, @Param("example") banthanhphanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banthanhphan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	int updateByExampleWithBLOBs(@Param("row") banthanhphan row, @Param("example") banthanhphanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banthanhphan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	int updateByExample(@Param("row") banthanhphan row, @Param("example") banthanhphanExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banthanhphan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	int updateByPrimaryKeySelective(banthanhphan row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banthanhphan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	int updateByPrimaryKeyWithBLOBs(banthanhphan row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banthanhphan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	int updateByPrimaryKey(banthanhphan row);
}