package com.anhkhoa.WebNT.mapper;

import com.anhkhoa.WebNT.model.chitietphieunhap;
import com.anhkhoa.WebNT.model.chitietphieunhapExample;
import com.anhkhoa.WebNT.model.chitietphieunhapKey;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface chitietphieunhapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chitietphieunhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    long countByExample(chitietphieunhapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chitietphieunhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    int deleteByExample(chitietphieunhapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chitietphieunhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    int deleteByPrimaryKey(chitietphieunhapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chitietphieunhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    int insert(chitietphieunhap row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chitietphieunhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    int insertSelective(chitietphieunhap row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chitietphieunhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    List<chitietphieunhap> selectByExample(chitietphieunhapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chitietphieunhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    chitietphieunhap selectByPrimaryKey(chitietphieunhapKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chitietphieunhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    int updateByExampleSelective(@Param("row") chitietphieunhap row, @Param("example") chitietphieunhapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chitietphieunhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    int updateByExample(@Param("row") chitietphieunhap row, @Param("example") chitietphieunhapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chitietphieunhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    int updateByPrimaryKeySelective(chitietphieunhap row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chitietphieunhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    int updateByPrimaryKey(chitietphieunhap row);
}