package com.anhkhoa.WebNT.mapper;

import com.anhkhoa.WebNT.model.phanxuong;
import com.anhkhoa.WebNT.model.phanxuongExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface phanxuongMapper {
    
    long countByExample(phanxuongExample example);

    int deleteByExample(phanxuongExample example);

    int deleteByPrimaryKey(Integer maphanxuong);

    int insert(phanxuong row);

    int insertSelective(phanxuong row);

    List<phanxuong> selectByExample(phanxuongExample example);

    phanxuong selectByPrimaryKey(Integer maphanxuong);

    int updateByExampleSelective(@Param("row") phanxuong row, @Param("example") phanxuongExample example);

    int updateByExample(@Param("row") phanxuong row, @Param("example") phanxuongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    int updateByPrimaryKeySelective(phanxuong row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    int updateByPrimaryKey(phanxuong row);
}