package com.anhkhoa.WebNT.mapper;

import com.anhkhoa.WebNT.model.phieunhap;
import com.anhkhoa.WebNT.model.phieunhapExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface phieunhapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieunhap
     *
     * @mbg.generated Thu Nov 02 15:54:30 ICT 2023
     */
    long countByExample(phieunhapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieunhap
     *
     * @mbg.generated Thu Nov 02 15:54:30 ICT 2023
     */
    int deleteByExample(phieunhapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieunhap
     *
     * @mbg.generated Thu Nov 02 15:54:30 ICT 2023
     */
    int deleteByPrimaryKey(Integer sophieunhap);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieunhap
     *
     * @mbg.generated Thu Nov 02 15:54:30 ICT 2023
     */
    int insert(phieunhap row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieunhap
     *
     * @mbg.generated Thu Nov 02 15:54:30 ICT 2023
     */
    int insertSelective(phieunhap row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieunhap
     *
     * @mbg.generated Thu Nov 02 15:54:30 ICT 2023
     */
    List<phieunhap> selectByExample(phieunhapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieunhap
     *
     * @mbg.generated Thu Nov 02 15:54:30 ICT 2023
     */
    phieunhap selectByPrimaryKey(Integer sophieunhap);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieunhap
     *
     * @mbg.generated Thu Nov 02 15:54:30 ICT 2023
     */
    int updateByExampleSelective(@Param("row") phieunhap row, @Param("example") phieunhapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieunhap
     *
     * @mbg.generated Thu Nov 02 15:54:30 ICT 2023
     */
    int updateByExample(@Param("row") phieunhap row, @Param("example") phieunhapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieunhap
     *
     * @mbg.generated Thu Nov 02 15:54:30 ICT 2023
     */
    int updateByPrimaryKeySelective(phieunhap row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieunhap
     *
     * @mbg.generated Thu Nov 02 15:54:30 ICT 2023
     */
    int updateByPrimaryKey(phieunhap row);
}