package com.anhkhoa.WebNT.mapper;

import com.anhkhoa.WebNT.model.sourceimage;
import com.anhkhoa.WebNT.model.sourceimageExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface sourceimageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sourceimage
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	long countByExample(sourceimageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sourceimage
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	int deleteByExample(sourceimageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sourceimage
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sourceimage
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	int insert(sourceimage row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sourceimage
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	int insertSelective(sourceimage row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sourceimage
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	List<sourceimage> selectByExample(sourceimageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sourceimage
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	sourceimage selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sourceimage
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	int updateByExampleSelective(@Param("row") sourceimage row, @Param("example") sourceimageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sourceimage
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	int updateByExample(@Param("row") sourceimage row, @Param("example") sourceimageExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sourceimage
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	int updateByPrimaryKeySelective(sourceimage row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sourceimage
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	int updateByPrimaryKey(sourceimage row);
}