package com.anhkhoa.WebNT.model;

public class account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.name
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.role
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.gmail
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    private String gmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.name
     *
     * @return the value of account.name
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.name
     *
     * @param name the value for account.name
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.password
     *
     * @return the value of account.password
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.password
     *
     * @param password the value for account.password
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.role
     *
     * @return the value of account.role
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.role
     *
     * @param role the value for account.role
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.gmail
     *
     * @return the value of account.gmail
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    public String getGmail() {
        return gmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.gmail
     *
     * @param gmail the value for account.gmail
     *
     * @mbg.generated Sat Nov 18 19:44:24 ICT 2023
     */
    public void setGmail(String gmail) {
        this.gmail = gmail;
    }
}