package com.anhkhoa.WebNT.model;

public class banthanhphan {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banthanhphan.MaBanThanhPhan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	private Integer mabanthanhphan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banthanhphan.TenBanThanhPhan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	private String tenbanthanhphan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banthanhphan.GiaBan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	private Integer giaban;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banthanhphan.MoTa
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	private String mota;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banthanhphan.MaBanThanhPhan
	 * @return  the value of banthanhphan.MaBanThanhPhan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	public Integer getMabanthanhphan() {
		return mabanthanhphan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banthanhphan.MaBanThanhPhan
	 * @param mabanthanhphan  the value for banthanhphan.MaBanThanhPhan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	public void setMabanthanhphan(Integer mabanthanhphan) {
		this.mabanthanhphan = mabanthanhphan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banthanhphan.TenBanThanhPhan
	 * @return  the value of banthanhphan.TenBanThanhPhan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	public String getTenbanthanhphan() {
		return tenbanthanhphan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banthanhphan.TenBanThanhPhan
	 * @param tenbanthanhphan  the value for banthanhphan.TenBanThanhPhan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	public void setTenbanthanhphan(String tenbanthanhphan) {
		this.tenbanthanhphan = tenbanthanhphan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banthanhphan.GiaBan
	 * @return  the value of banthanhphan.GiaBan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	public Integer getGiaban() {
		return giaban;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banthanhphan.GiaBan
	 * @param giaban  the value for banthanhphan.GiaBan
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	public void setGiaban(Integer giaban) {
		this.giaban = giaban;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banthanhphan.MoTa
	 * @return  the value of banthanhphan.MoTa
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	public String getMota() {
		return mota;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banthanhphan.MoTa
	 * @param mota  the value for banthanhphan.MoTa
	 * @mbg.generated  Sat Nov 18 19:44:05 ICT 2023
	 */
	public void setMota(String mota) {
		this.mota = mota;
	}
}