package com.anhkhoa.WebNT.model;

public class chitietphieuxuatKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chitietphieuxuat.SoPhieuXuat
     *
     * @mbg.generated Mon Nov 06 21:00:07 ICT 2023
     */
    private Integer sophieuxuat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chitietphieuxuat.MaBanThanhPhan
     *
     * @mbg.generated Mon Nov 06 21:00:07 ICT 2023
     */
    private Integer mabanthanhphan;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chitietphieuxuat.SoPhieuXuat
     *
     * @return the value of chitietphieuxuat.SoPhieuXuat
     *
     * @mbg.generated Mon Nov 06 21:00:07 ICT 2023
     */
    public Integer getSophieuxuat() {
        return sophieuxuat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chitietphieuxuat.SoPhieuXuat
     *
     * @param sophieuxuat the value for chitietphieuxuat.SoPhieuXuat
     *
     * @mbg.generated Mon Nov 06 21:00:07 ICT 2023
     */
    public void setSophieuxuat(Integer sophieuxuat) {
        this.sophieuxuat = sophieuxuat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chitietphieuxuat.MaBanThanhPhan
     *
     * @return the value of chitietphieuxuat.MaBanThanhPhan
     *
     * @mbg.generated Mon Nov 06 21:00:07 ICT 2023
     */
    public Integer getMabanthanhphan() {
        return mabanthanhphan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chitietphieuxuat.MaBanThanhPhan
     *
     * @param mabanthanhphan the value for chitietphieuxuat.MaBanThanhPhan
     *
     * @mbg.generated Mon Nov 06 21:00:07 ICT 2023
     */
    public void setMabanthanhphan(Integer mabanthanhphan) {
        this.mabanthanhphan = mabanthanhphan;
    }
}