package com.anhkhoa.WebNT.model;

public class chitietphieunhap extends chitietphieunhapKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chitietphieunhap.SoLuong
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    private Integer soluong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chitietphieunhap.GiaNhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    private Integer gianhap;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chitietphieunhap.SoLuong
     *
     * @return the value of chitietphieunhap.SoLuong
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    public Integer getSoluong() {
        return soluong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chitietphieunhap.SoLuong
     *
     * @param soluong the value for chitietphieunhap.SoLuong
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    public void setSoluong(Integer soluong) {
        this.soluong = soluong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chitietphieunhap.GiaNhap
     *
     * @return the value of chitietphieunhap.GiaNhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    public Integer getGianhap() {
        return gianhap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chitietphieunhap.GiaNhap
     *
     * @param gianhap the value for chitietphieunhap.GiaNhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    public void setGianhap(Integer gianhap) {
        this.gianhap = gianhap;
    }
}