package com.anhkhoa.WebNT.model;

public class chitietphieunhapKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chitietphieunhap.SoPhieuNhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    private Integer sophieunhap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chitietphieunhap.MaBanThanhPhan
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    private Integer mabanthanhphan;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chitietphieunhap.SoPhieuNhap
     *
     * @return the value of chitietphieunhap.SoPhieuNhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    public Integer getSophieunhap() {
        return sophieunhap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chitietphieunhap.SoPhieuNhap
     *
     * @param sophieunhap the value for chitietphieunhap.SoPhieuNhap
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    public void setSophieunhap(Integer sophieunhap) {
        this.sophieunhap = sophieunhap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chitietphieunhap.MaBanThanhPhan
     *
     * @return the value of chitietphieunhap.MaBanThanhPhan
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    public Integer getMabanthanhphan() {
        return mabanthanhphan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chitietphieunhap.MaBanThanhPhan
     *
     * @param mabanthanhphan the value for chitietphieunhap.MaBanThanhPhan
     *
     * @mbg.generated Thu Nov 02 15:52:59 ICT 2023
     */
    public void setMabanthanhphan(Integer mabanthanhphan) {
        this.mabanthanhphan = mabanthanhphan;
    }
}