package com.anhkhoa.WebNT.model;

import java.util.ArrayList;
import java.util.List;


public class khachhangExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table khachhang
	 * @mbg.generated  Thu Nov 02 15:55:17 ICT 2023
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table khachhang
	 * @mbg.generated  Thu Nov 02 15:55:17 ICT 2023
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table khachhang
	 * @mbg.generated  Thu Nov 02 15:55:17 ICT 2023
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khachhang
	 * @mbg.generated  Thu Nov 02 15:55:17 ICT 2023
	 */
	public khachhangExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khachhang
	 * @mbg.generated  Thu Nov 02 15:55:17 ICT 2023
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khachhang
	 * @mbg.generated  Thu Nov 02 15:55:17 ICT 2023
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khachhang
	 * @mbg.generated  Thu Nov 02 15:55:17 ICT 2023
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khachhang
	 * @mbg.generated  Thu Nov 02 15:55:17 ICT 2023
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khachhang
	 * @mbg.generated  Thu Nov 02 15:55:17 ICT 2023
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khachhang
	 * @mbg.generated  Thu Nov 02 15:55:17 ICT 2023
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khachhang
	 * @mbg.generated  Thu Nov 02 15:55:17 ICT 2023
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khachhang
	 * @mbg.generated  Thu Nov 02 15:55:17 ICT 2023
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khachhang
	 * @mbg.generated  Thu Nov 02 15:55:17 ICT 2023
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table khachhang
	 * @mbg.generated  Thu Nov 02 15:55:17 ICT 2023
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table khachhang
	 * @mbg.generated  Thu Nov 02 15:55:17 ICT 2023
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMakhIsNull() {
			addCriterion("MaKH is null");
			return (Criteria) this;
		}

		public Criteria andMakhIsNotNull() {
			addCriterion("MaKH is not null");
			return (Criteria) this;
		}

		public Criteria andMakhEqualTo(Integer value) {
			addCriterion("MaKH =", value, "makh");
			return (Criteria) this;
		}

		public Criteria andMakhNotEqualTo(Integer value) {
			addCriterion("MaKH <>", value, "makh");
			return (Criteria) this;
		}

		public Criteria andMakhGreaterThan(Integer value) {
			addCriterion("MaKH >", value, "makh");
			return (Criteria) this;
		}

		public Criteria andMakhGreaterThanOrEqualTo(Integer value) {
			addCriterion("MaKH >=", value, "makh");
			return (Criteria) this;
		}

		public Criteria andMakhLessThan(Integer value) {
			addCriterion("MaKH <", value, "makh");
			return (Criteria) this;
		}

		public Criteria andMakhLessThanOrEqualTo(Integer value) {
			addCriterion("MaKH <=", value, "makh");
			return (Criteria) this;
		}

		public Criteria andMakhIn(List<Integer> values) {
			addCriterion("MaKH in", values, "makh");
			return (Criteria) this;
		}

		public Criteria andMakhNotIn(List<Integer> values) {
			addCriterion("MaKH not in", values, "makh");
			return (Criteria) this;
		}

		public Criteria andMakhBetween(Integer value1, Integer value2) {
			addCriterion("MaKH between", value1, value2, "makh");
			return (Criteria) this;
		}

		public Criteria andMakhNotBetween(Integer value1, Integer value2) {
			addCriterion("MaKH not between", value1, value2, "makh");
			return (Criteria) this;
		}

		public Criteria andTenkhIsNull() {
			addCriterion("TenKH is null");
			return (Criteria) this;
		}

		public Criteria andTenkhIsNotNull() {
			addCriterion("TenKH is not null");
			return (Criteria) this;
		}

		public Criteria andTenkhEqualTo(String value) {
			addCriterion("TenKH =", value, "tenkh");
			return (Criteria) this;
		}

		public Criteria andTenkhNotEqualTo(String value) {
			addCriterion("TenKH <>", value, "tenkh");
			return (Criteria) this;
		}

		public Criteria andTenkhGreaterThan(String value) {
			addCriterion("TenKH >", value, "tenkh");
			return (Criteria) this;
		}

		public Criteria andTenkhGreaterThanOrEqualTo(String value) {
			addCriterion("TenKH >=", value, "tenkh");
			return (Criteria) this;
		}

		public Criteria andTenkhLessThan(String value) {
			addCriterion("TenKH <", value, "tenkh");
			return (Criteria) this;
		}

		public Criteria andTenkhLessThanOrEqualTo(String value) {
			addCriterion("TenKH <=", value, "tenkh");
			return (Criteria) this;
		}

		public Criteria andTenkhLike(String value) {
			addCriterion("TenKH like", value, "tenkh");
			return (Criteria) this;
		}

		public Criteria andTenkhNotLike(String value) {
			addCriterion("TenKH not like", value, "tenkh");
			return (Criteria) this;
		}

		public Criteria andTenkhIn(List<String> values) {
			addCriterion("TenKH in", values, "tenkh");
			return (Criteria) this;
		}

		public Criteria andTenkhNotIn(List<String> values) {
			addCriterion("TenKH not in", values, "tenkh");
			return (Criteria) this;
		}

		public Criteria andTenkhBetween(String value1, String value2) {
			addCriterion("TenKH between", value1, value2, "tenkh");
			return (Criteria) this;
		}

		public Criteria andTenkhNotBetween(String value1, String value2) {
			addCriterion("TenKH not between", value1, value2, "tenkh");
			return (Criteria) this;
		}

		public Criteria andSdtIsNull() {
			addCriterion("SDT is null");
			return (Criteria) this;
		}

		public Criteria andSdtIsNotNull() {
			addCriterion("SDT is not null");
			return (Criteria) this;
		}

		public Criteria andSdtEqualTo(String value) {
			addCriterion("SDT =", value, "sdt");
			return (Criteria) this;
		}

		public Criteria andSdtNotEqualTo(String value) {
			addCriterion("SDT <>", value, "sdt");
			return (Criteria) this;
		}

		public Criteria andSdtGreaterThan(String value) {
			addCriterion("SDT >", value, "sdt");
			return (Criteria) this;
		}

		public Criteria andSdtGreaterThanOrEqualTo(String value) {
			addCriterion("SDT >=", value, "sdt");
			return (Criteria) this;
		}

		public Criteria andSdtLessThan(String value) {
			addCriterion("SDT <", value, "sdt");
			return (Criteria) this;
		}

		public Criteria andSdtLessThanOrEqualTo(String value) {
			addCriterion("SDT <=", value, "sdt");
			return (Criteria) this;
		}

		public Criteria andSdtLike(String value) {
			addCriterion("SDT like", value, "sdt");
			return (Criteria) this;
		}

		public Criteria andSdtNotLike(String value) {
			addCriterion("SDT not like", value, "sdt");
			return (Criteria) this;
		}

		public Criteria andSdtIn(List<String> values) {
			addCriterion("SDT in", values, "sdt");
			return (Criteria) this;
		}

		public Criteria andSdtNotIn(List<String> values) {
			addCriterion("SDT not in", values, "sdt");
			return (Criteria) this;
		}

		public Criteria andSdtBetween(String value1, String value2) {
			addCriterion("SDT between", value1, value2, "sdt");
			return (Criteria) this;
		}

		public Criteria andSdtNotBetween(String value1, String value2) {
			addCriterion("SDT not between", value1, value2, "sdt");
			return (Criteria) this;
		}

		public Criteria andDiachiIsNull() {
			addCriterion("DiaChi is null");
			return (Criteria) this;
		}

		public Criteria andDiachiIsNotNull() {
			addCriterion("DiaChi is not null");
			return (Criteria) this;
		}

		public Criteria andDiachiEqualTo(String value) {
			addCriterion("DiaChi =", value, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiNotEqualTo(String value) {
			addCriterion("DiaChi <>", value, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiGreaterThan(String value) {
			addCriterion("DiaChi >", value, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiGreaterThanOrEqualTo(String value) {
			addCriterion("DiaChi >=", value, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiLessThan(String value) {
			addCriterion("DiaChi <", value, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiLessThanOrEqualTo(String value) {
			addCriterion("DiaChi <=", value, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiLike(String value) {
			addCriterion("DiaChi like", value, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiNotLike(String value) {
			addCriterion("DiaChi not like", value, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiIn(List<String> values) {
			addCriterion("DiaChi in", values, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiNotIn(List<String> values) {
			addCriterion("DiaChi not in", values, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiBetween(String value1, String value2) {
			addCriterion("DiaChi between", value1, value2, "diachi");
			return (Criteria) this;
		}

		public Criteria andDiachiNotBetween(String value1, String value2) {
			addCriterion("DiaChi not between", value1, value2, "diachi");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table khachhang
	 * @mbg.generated  Thu Nov 02 15:55:17 ICT 2023
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table khachhang
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 02 15:55:17 ICT 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}