package com.anhkhoa.WebNT.model;

public class phanxuong {

    private Integer maphanxuong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phanxuong.TenPhanXuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    private String tenphanxuong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phanxuong.HoTenQuanDoc
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    private String hotenquandoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phanxuong.avt
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    private String avt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phanxuong.MaPhanXuong
     *
     * @return the value of phanxuong.MaPhanXuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public Integer getMaphanxuong() {
        return maphanxuong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phanxuong.MaPhanXuong
     *
     * @param maphanxuong the value for phanxuong.MaPhanXuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public void setMaphanxuong(Integer maphanxuong) {
        this.maphanxuong = maphanxuong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phanxuong.TenPhanXuong
     *
     * @return the value of phanxuong.TenPhanXuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public String getTenphanxuong() {
        return tenphanxuong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phanxuong.TenPhanXuong
     *
     * @param tenphanxuong the value for phanxuong.TenPhanXuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public void setTenphanxuong(String tenphanxuong) {
        this.tenphanxuong = tenphanxuong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phanxuong.HoTenQuanDoc
     *
     * @return the value of phanxuong.HoTenQuanDoc
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public String getHotenquandoc() {
        return hotenquandoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phanxuong.HoTenQuanDoc
     *
     * @param hotenquandoc the value for phanxuong.HoTenQuanDoc
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public void setHotenquandoc(String hotenquandoc) {
        this.hotenquandoc = hotenquandoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phanxuong.avt
     *
     * @return the value of phanxuong.avt
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public String getAvt() {
        return avt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phanxuong.avt
     *
     * @param avt the value for phanxuong.avt
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public void setAvt(String avt) {
        this.avt = avt;
    }
}