package com.anhkhoa.WebNT.model;

import java.util.ArrayList;
import java.util.List;

public class phanxuongExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public phanxuongExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMaphanxuongIsNull() {
            addCriterion("MaPhanXuong is null");
            return (Criteria) this;
        }

        public Criteria andMaphanxuongIsNotNull() {
            addCriterion("MaPhanXuong is not null");
            return (Criteria) this;
        }

        public Criteria andMaphanxuongEqualTo(Integer value) {
            addCriterion("MaPhanXuong =", value, "maphanxuong");
            return (Criteria) this;
        }

        public Criteria andMaphanxuongNotEqualTo(Integer value) {
            addCriterion("MaPhanXuong <>", value, "maphanxuong");
            return (Criteria) this;
        }

        public Criteria andMaphanxuongGreaterThan(Integer value) {
            addCriterion("MaPhanXuong >", value, "maphanxuong");
            return (Criteria) this;
        }

        public Criteria andMaphanxuongGreaterThanOrEqualTo(Integer value) {
            addCriterion("MaPhanXuong >=", value, "maphanxuong");
            return (Criteria) this;
        }

        public Criteria andMaphanxuongLessThan(Integer value) {
            addCriterion("MaPhanXuong <", value, "maphanxuong");
            return (Criteria) this;
        }

        public Criteria andMaphanxuongLessThanOrEqualTo(Integer value) {
            addCriterion("MaPhanXuong <=", value, "maphanxuong");
            return (Criteria) this;
        }

        public Criteria andMaphanxuongIn(List<Integer> values) {
            addCriterion("MaPhanXuong in", values, "maphanxuong");
            return (Criteria) this;
        }

        public Criteria andMaphanxuongNotIn(List<Integer> values) {
            addCriterion("MaPhanXuong not in", values, "maphanxuong");
            return (Criteria) this;
        }

        public Criteria andMaphanxuongBetween(Integer value1, Integer value2) {
            addCriterion("MaPhanXuong between", value1, value2, "maphanxuong");
            return (Criteria) this;
        }

        public Criteria andMaphanxuongNotBetween(Integer value1, Integer value2) {
            addCriterion("MaPhanXuong not between", value1, value2, "maphanxuong");
            return (Criteria) this;
        }

        public Criteria andTenphanxuongIsNull() {
            addCriterion("TenPhanXuong is null");
            return (Criteria) this;
        }

        public Criteria andTenphanxuongIsNotNull() {
            addCriterion("TenPhanXuong is not null");
            return (Criteria) this;
        }

        public Criteria andTenphanxuongEqualTo(String value) {
            addCriterion("TenPhanXuong =", value, "tenphanxuong");
            return (Criteria) this;
        }

        public Criteria andTenphanxuongNotEqualTo(String value) {
            addCriterion("TenPhanXuong <>", value, "tenphanxuong");
            return (Criteria) this;
        }

        public Criteria andTenphanxuongGreaterThan(String value) {
            addCriterion("TenPhanXuong >", value, "tenphanxuong");
            return (Criteria) this;
        }

        public Criteria andTenphanxuongGreaterThanOrEqualTo(String value) {
            addCriterion("TenPhanXuong >=", value, "tenphanxuong");
            return (Criteria) this;
        }

        public Criteria andTenphanxuongLessThan(String value) {
            addCriterion("TenPhanXuong <", value, "tenphanxuong");
            return (Criteria) this;
        }

        public Criteria andTenphanxuongLessThanOrEqualTo(String value) {
            addCriterion("TenPhanXuong <=", value, "tenphanxuong");
            return (Criteria) this;
        }

        public Criteria andTenphanxuongLike(String value) {
            addCriterion("TenPhanXuong like", value, "tenphanxuong");
            return (Criteria) this;
        }

        public Criteria andTenphanxuongNotLike(String value) {
            addCriterion("TenPhanXuong not like", value, "tenphanxuong");
            return (Criteria) this;
        }

        public Criteria andTenphanxuongIn(List<String> values) {
            addCriterion("TenPhanXuong in", values, "tenphanxuong");
            return (Criteria) this;
        }

        public Criteria andTenphanxuongNotIn(List<String> values) {
            addCriterion("TenPhanXuong not in", values, "tenphanxuong");
            return (Criteria) this;
        }

        public Criteria andTenphanxuongBetween(String value1, String value2) {
            addCriterion("TenPhanXuong between", value1, value2, "tenphanxuong");
            return (Criteria) this;
        }

        public Criteria andTenphanxuongNotBetween(String value1, String value2) {
            addCriterion("TenPhanXuong not between", value1, value2, "tenphanxuong");
            return (Criteria) this;
        }

        public Criteria andHotenquandocIsNull() {
            addCriterion("HoTenQuanDoc is null");
            return (Criteria) this;
        }

        public Criteria andHotenquandocIsNotNull() {
            addCriterion("HoTenQuanDoc is not null");
            return (Criteria) this;
        }

        public Criteria andHotenquandocEqualTo(String value) {
            addCriterion("HoTenQuanDoc =", value, "hotenquandoc");
            return (Criteria) this;
        }

        public Criteria andHotenquandocNotEqualTo(String value) {
            addCriterion("HoTenQuanDoc <>", value, "hotenquandoc");
            return (Criteria) this;
        }

        public Criteria andHotenquandocGreaterThan(String value) {
            addCriterion("HoTenQuanDoc >", value, "hotenquandoc");
            return (Criteria) this;
        }

        public Criteria andHotenquandocGreaterThanOrEqualTo(String value) {
            addCriterion("HoTenQuanDoc >=", value, "hotenquandoc");
            return (Criteria) this;
        }

        public Criteria andHotenquandocLessThan(String value) {
            addCriterion("HoTenQuanDoc <", value, "hotenquandoc");
            return (Criteria) this;
        }

        public Criteria andHotenquandocLessThanOrEqualTo(String value) {
            addCriterion("HoTenQuanDoc <=", value, "hotenquandoc");
            return (Criteria) this;
        }

        public Criteria andHotenquandocLike(String value) {
            addCriterion("HoTenQuanDoc like", value, "hotenquandoc");
            return (Criteria) this;
        }

        public Criteria andHotenquandocNotLike(String value) {
            addCriterion("HoTenQuanDoc not like", value, "hotenquandoc");
            return (Criteria) this;
        }

        public Criteria andHotenquandocIn(List<String> values) {
            addCriterion("HoTenQuanDoc in", values, "hotenquandoc");
            return (Criteria) this;
        }

        public Criteria andHotenquandocNotIn(List<String> values) {
            addCriterion("HoTenQuanDoc not in", values, "hotenquandoc");
            return (Criteria) this;
        }

        public Criteria andHotenquandocBetween(String value1, String value2) {
            addCriterion("HoTenQuanDoc between", value1, value2, "hotenquandoc");
            return (Criteria) this;
        }

        public Criteria andHotenquandocNotBetween(String value1, String value2) {
            addCriterion("HoTenQuanDoc not between", value1, value2, "hotenquandoc");
            return (Criteria) this;
        }

        public Criteria andAvtIsNull() {
            addCriterion("avt is null");
            return (Criteria) this;
        }

        public Criteria andAvtIsNotNull() {
            addCriterion("avt is not null");
            return (Criteria) this;
        }

        public Criteria andAvtEqualTo(String value) {
            addCriterion("avt =", value, "avt");
            return (Criteria) this;
        }

        public Criteria andAvtNotEqualTo(String value) {
            addCriterion("avt <>", value, "avt");
            return (Criteria) this;
        }

        public Criteria andAvtGreaterThan(String value) {
            addCriterion("avt >", value, "avt");
            return (Criteria) this;
        }

        public Criteria andAvtGreaterThanOrEqualTo(String value) {
            addCriterion("avt >=", value, "avt");
            return (Criteria) this;
        }

        public Criteria andAvtLessThan(String value) {
            addCriterion("avt <", value, "avt");
            return (Criteria) this;
        }

        public Criteria andAvtLessThanOrEqualTo(String value) {
            addCriterion("avt <=", value, "avt");
            return (Criteria) this;
        }

        public Criteria andAvtLike(String value) {
            addCriterion("avt like", value, "avt");
            return (Criteria) this;
        }

        public Criteria andAvtNotLike(String value) {
            addCriterion("avt not like", value, "avt");
            return (Criteria) this;
        }

        public Criteria andAvtIn(List<String> values) {
            addCriterion("avt in", values, "avt");
            return (Criteria) this;
        }

        public Criteria andAvtNotIn(List<String> values) {
            addCriterion("avt not in", values, "avt");
            return (Criteria) this;
        }

        public Criteria andAvtBetween(String value1, String value2) {
            addCriterion("avt between", value1, value2, "avt");
            return (Criteria) this;
        }

        public Criteria andAvtNotBetween(String value1, String value2) {
            addCriterion("avt not between", value1, value2, "avt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table phanxuong
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 02 15:54:54 ICT 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table phanxuong
     *
     * @mbg.generated Thu Nov 02 15:54:54 ICT 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}