package com.anhkhoa.WebNT.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class phieuxuatExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phieuxuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phieuxuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phieuxuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieuxuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public phieuxuatExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieuxuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieuxuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieuxuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieuxuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieuxuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieuxuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieuxuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieuxuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieuxuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table phieuxuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table phieuxuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andSophieuxuatIsNull() {
            addCriterion("SoPhieuXuat is null");
            return (Criteria) this;
        }

        public Criteria andSophieuxuatIsNotNull() {
            addCriterion("SoPhieuXuat is not null");
            return (Criteria) this;
        }

        public Criteria andSophieuxuatEqualTo(Integer value) {
            addCriterion("SoPhieuXuat =", value, "sophieuxuat");
            return (Criteria) this;
        }

        public Criteria andSophieuxuatNotEqualTo(Integer value) {
            addCriterion("SoPhieuXuat <>", value, "sophieuxuat");
            return (Criteria) this;
        }

        public Criteria andSophieuxuatGreaterThan(Integer value) {
            addCriterion("SoPhieuXuat >", value, "sophieuxuat");
            return (Criteria) this;
        }

        public Criteria andSophieuxuatGreaterThanOrEqualTo(Integer value) {
            addCriterion("SoPhieuXuat >=", value, "sophieuxuat");
            return (Criteria) this;
        }

        public Criteria andSophieuxuatLessThan(Integer value) {
            addCriterion("SoPhieuXuat <", value, "sophieuxuat");
            return (Criteria) this;
        }

        public Criteria andSophieuxuatLessThanOrEqualTo(Integer value) {
            addCriterion("SoPhieuXuat <=", value, "sophieuxuat");
            return (Criteria) this;
        }

        public Criteria andSophieuxuatIn(List<Integer> values) {
            addCriterion("SoPhieuXuat in", values, "sophieuxuat");
            return (Criteria) this;
        }

        public Criteria andSophieuxuatNotIn(List<Integer> values) {
            addCriterion("SoPhieuXuat not in", values, "sophieuxuat");
            return (Criteria) this;
        }

        public Criteria andSophieuxuatBetween(Integer value1, Integer value2) {
            addCriterion("SoPhieuXuat between", value1, value2, "sophieuxuat");
            return (Criteria) this;
        }

        public Criteria andSophieuxuatNotBetween(Integer value1, Integer value2) {
            addCriterion("SoPhieuXuat not between", value1, value2, "sophieuxuat");
            return (Criteria) this;
        }

        public Criteria andNgayphieuxuatIsNull() {
            addCriterion("NgayPhieuXuat is null");
            return (Criteria) this;
        }

        public Criteria andNgayphieuxuatIsNotNull() {
            addCriterion("NgayPhieuXuat is not null");
            return (Criteria) this;
        }

        public Criteria andNgayphieuxuatEqualTo(Date value) {
            addCriterionForJDBCDate("NgayPhieuXuat =", value, "ngayphieuxuat");
            return (Criteria) this;
        }

        public Criteria andNgayphieuxuatNotEqualTo(Date value) {
            addCriterionForJDBCDate("NgayPhieuXuat <>", value, "ngayphieuxuat");
            return (Criteria) this;
        }

        public Criteria andNgayphieuxuatGreaterThan(Date value) {
            addCriterionForJDBCDate("NgayPhieuXuat >", value, "ngayphieuxuat");
            return (Criteria) this;
        }

        public Criteria andNgayphieuxuatGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("NgayPhieuXuat >=", value, "ngayphieuxuat");
            return (Criteria) this;
        }

        public Criteria andNgayphieuxuatLessThan(Date value) {
            addCriterionForJDBCDate("NgayPhieuXuat <", value, "ngayphieuxuat");
            return (Criteria) this;
        }

        public Criteria andNgayphieuxuatLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("NgayPhieuXuat <=", value, "ngayphieuxuat");
            return (Criteria) this;
        }

        public Criteria andNgayphieuxuatIn(List<Date> values) {
            addCriterionForJDBCDate("NgayPhieuXuat in", values, "ngayphieuxuat");
            return (Criteria) this;
        }

        public Criteria andNgayphieuxuatNotIn(List<Date> values) {
            addCriterionForJDBCDate("NgayPhieuXuat not in", values, "ngayphieuxuat");
            return (Criteria) this;
        }

        public Criteria andNgayphieuxuatBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("NgayPhieuXuat between", value1, value2, "ngayphieuxuat");
            return (Criteria) this;
        }

        public Criteria andNgayphieuxuatNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("NgayPhieuXuat not between", value1, value2, "ngayphieuxuat");
            return (Criteria) this;
        }

        public Criteria andMakhIsNull() {
            addCriterion("MaKH is null");
            return (Criteria) this;
        }

        public Criteria andMakhIsNotNull() {
            addCriterion("MaKH is not null");
            return (Criteria) this;
        }

        public Criteria andMakhEqualTo(Integer value) {
            addCriterion("MaKH =", value, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhNotEqualTo(Integer value) {
            addCriterion("MaKH <>", value, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhGreaterThan(Integer value) {
            addCriterion("MaKH >", value, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhGreaterThanOrEqualTo(Integer value) {
            addCriterion("MaKH >=", value, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhLessThan(Integer value) {
            addCriterion("MaKH <", value, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhLessThanOrEqualTo(Integer value) {
            addCriterion("MaKH <=", value, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhIn(List<Integer> values) {
            addCriterion("MaKH in", values, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhNotIn(List<Integer> values) {
            addCriterion("MaKH not in", values, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhBetween(Integer value1, Integer value2) {
            addCriterion("MaKH between", value1, value2, "makh");
            return (Criteria) this;
        }

        public Criteria andMakhNotBetween(Integer value1, Integer value2) {
            addCriterion("MaKH not between", value1, value2, "makh");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table phieuxuat
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 02 15:54:13 ICT 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table phieuxuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}