package com.anhkhoa.WebNT.model;

import java.util.Date;

public class phieuxuat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phieuxuat.SoPhieuXuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    private Integer sophieuxuat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phieuxuat.NgayPhieuXuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    private Date ngayphieuxuat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phieuxuat.MaKH
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    private Integer makh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phieuxuat.SoPhieuXuat
     *
     * @return the value of phieuxuat.SoPhieuXuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public Integer getSophieuxuat() {
        return sophieuxuat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phieuxuat.SoPhieuXuat
     *
     * @param sophieuxuat the value for phieuxuat.SoPhieuXuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public void setSophieuxuat(Integer sophieuxuat) {
        this.sophieuxuat = sophieuxuat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phieuxuat.NgayPhieuXuat
     *
     * @return the value of phieuxuat.NgayPhieuXuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public Date getNgayphieuxuat() {
        return ngayphieuxuat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phieuxuat.NgayPhieuXuat
     *
     * @param ngayphieuxuat the value for phieuxuat.NgayPhieuXuat
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public void setNgayphieuxuat(Date ngayphieuxuat) {
        this.ngayphieuxuat = ngayphieuxuat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phieuxuat.MaKH
     *
     * @return the value of phieuxuat.MaKH
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public Integer getMakh() {
        return makh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phieuxuat.MaKH
     *
     * @param makh the value for phieuxuat.MaKH
     *
     * @mbg.generated Thu Nov 02 15:54:13 ICT 2023
     */
    public void setMakh(Integer makh) {
        this.makh = makh;
    }
}