package com.anhkhoa.WebNT.model;

public class sourceimage {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sourceimage.id
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sourceimage.MaBanThanhPhan
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	private Integer mabanthanhphan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sourceimage.linkimg
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	private String linkimg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sourceimage.id
	 * @return  the value of sourceimage.id
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sourceimage.id
	 * @param id  the value for sourceimage.id
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sourceimage.MaBanThanhPhan
	 * @return  the value of sourceimage.MaBanThanhPhan
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	public Integer getMabanthanhphan() {
		return mabanthanhphan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sourceimage.MaBanThanhPhan
	 * @param mabanthanhphan  the value for sourceimage.MaBanThanhPhan
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	public void setMabanthanhphan(Integer mabanthanhphan) {
		this.mabanthanhphan = mabanthanhphan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sourceimage.linkimg
	 * @return  the value of sourceimage.linkimg
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	public String getLinkimg() {
		return linkimg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sourceimage.linkimg
	 * @param linkimg  the value for sourceimage.linkimg
	 * @mbg.generated  Fri Nov 17 07:39:14 ICT 2023
	 */
	public void setLinkimg(String linkimg) {
		this.linkimg = linkimg;
	}
}